import Head from 'next/head'
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <div className="container">
      <div className="content">
        <Link href="#">
          <a>Avenger Assemble</a>
        </Link>
      </div>
    </div>

      </main>


    </div>
  )
}
